services:
  dashboard_mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbUser
      MONGO_INITDB_ROOT_PASSWORD: SecurePassword
      MONGO_INITDB_DATABASE: AwesomeDashboard
    ports:
      - 27017:27017
    volumes:
      - dashboard_mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  dashboard_mongodb_data:
